# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: Bazarr (Skayo)

    # Description displayed on the app list
    description: |-
        Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            ![Bazarr Logo](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr.png)

            🌐 [Website](https://www.bazarr.media/)
            📖 [Documentation](https://wiki.bazarr.media/)
            📁 [GitHub](https://github.com/morpheus65535/bazarr)
            🐳 [DockerHub](https://hub.docker.com/r/linuxserver/bazarr)
            👛 [Donate](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url)

            Bazarr is a companion application to Sonarr and Radarr.
            It manages and downloads subtitles based on your requirements.
            You define your preferences by TV show or movie and Bazarr takes care of everything for you.

            Be aware that Bazarr doesn't scan disk to detect series and movies: It only takes care of the series and movies that are indexed in Sonarr and Radarr.

        # Displayed after deployment
        end: |-
            🎉🎉🎉 Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

    # Documentation Link
    documentation: https://wiki.bazarr.media/

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag to install.  
                Click [here](https://hub.docker.com/r/linuxserver/bazarr/tags) for a list of available tags.
            defaultValue: 1.0.1
            validRegex: /^(?:(?:arm|amd)(?:64|32)(?:v\d+)?-)?(?:develop(?:ment)?-?|nightly-?)?(?:version-)?v?\d+\.\d+\.\d+(?:-beta\.\d+)?(?:-ls\d+)?$/

        # Variable for media path
        -   id: $$cap_media_path
            label: Media Path
            description: |-
                Specify the location of all your media (movies, TV shows, music, etc.).
            validRegex: /^(?:[a-zA-Z]:)?[\/\\]{0,2}(?:[.\/\\ ](?![.\/\\\n])|[^<>:"|?*.\/\\ \n])+$/

        # Variable for time zone
        -   id: $$cap_tz
            label: Time Zone
            description: |-
                Specify your system's time zone.  
                Click [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of available time zones.
            defaultValue: Europe/Vienna
            validRegex: /^\w+\/\w+$/

        # Variable for Process User ID
        -   id: $$cap_puid
            label: User ID
            description: |-
                Specify the User ID that the process should use.  
                Run `id <username>` on the host system to see your UID.
            defaultValue: 1000
            validRegex: /^-?\d+$/

        # Variable for Process Group ID
        -   id: $$cap_pgid
            label: Group ID
            description: |-
                Specify the Group ID that the process should use.  
                Run `id <username>` on the host system to see your GID.
            defaultValue: 1000
            validRegex: /^-?\d+$/


# Define services
services:

    # Bazarr service
    $$cap_appname:

        # Use image by linuxserver.io
        image: lscr.io/linuxserver/bazarr:$$cap_appversion

        # Set hostname (f.e. bazarr.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # Process User ID
            PUID: $$cap_puid

            # Process Group ID
            PGID: $$cap_pgid

            # Timezone
            TZ: $$cap_tz

        # Define volumes
        volumes:

            # Volume containing database data and config
            - $$cap_appname-config:/config

            # Volume containing media like movies and TV shows
            - $$cap_media_path:/data/media

        # CapRover's special options
        caproverExtra:

            # Bazarr uses port 6767
            containerHttpPort: 6767
