# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: Photoview (Skayo)

    # Description displayed on the app list
    description: |-
        Photo gallery for self-hosted personal servers

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            ![Photoview Logo](https://github.com/photoview/photoview/raw/master/screenshots/photoview-logo.svg)

            🌐 [Website](https://photoview.github.io/)
            📖 [Documentation](https://photoview.github.io/docs)
            📁 [GitHub](https://github.com/photoview/photoview)
            🐳 [DockerHub](https://hub.docker.com/r/viktorstrate/photoview)
            👛 [Donate](https://github.com/sponsors/viktorstrate)

            Photoview is a simple and user-friendly photo gallery that's made for photographers and aims to provide an easy and fast way to navigate directories, with thousands of high-resolution photos.

            You configure Photoview to look for photos and videos within a directory on your file system.
            The scanner automatically picks up your media and start to generate thumbnail images to make browsing super fast.

            When your media has been scanned they show up on the website, organised in the same way as on the filesystem.

        # Displayed after deployment
        end: |-
            🎉🎉🎉 Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

    # Documentation Link
    documentation: https://photoview.github.io/docs

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for Photoview Version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag of Photoview to install.  
                Click [here](https://hub.docker.com/r/linuxserver/sonarr/tags) for a list of available tags.
            defaultValue: 2.0.1
            validRegex: /^(?:\d+(?:\.\d+(?:\.\d+)?)?|linux)(?:-(?:arm|amd)(?:64|32)?(?:-v\d+)?(?:-[a-z0-9]+-push)?)?$/

        # Variable for Media Path
        -   id: $$cap_media_path
            label: Media Path
            description: |-
                Specify the location of all your photos and videos.
            validRegex: /^(?:[a-zA-Z]:)?[\/\\]{0,2}(?:[.\/\\ ](?![.\/\\\n])|[^<>:"|?*.\/\\ \n])+$/

        # Variable for Mapbox Token
        -   id: $$cap_mapbox_token
            label: Mapbox Token (OPTIONAL)
            description: |-
                To enable map related features, you need to create a mapbox token.  
                A token can be generated for free [here](https://account.mapbox.com/access-tokens/).  
                It's a good idea to limit the scope of the token to your own domain, to prevent others from using it.  
                Leave empty to disable map related features.

        # Variable for MariaDB Version
        -   id: $$cap_mariadb_appversion
            label: MariaDB Version
            description: |-
                Specify the version tag of MariaDB to install.  
                Click [here](https://hub.docker.com/r/library/mariadb/tags) for a list of available tags.
            defaultValue: 10.5
            validRegex: /^(?:\d+(?:\.\d+(?:\.\d+)?)?|rc|alpha)(?:-\w+)?$/

        # Variable for MariaDB Database Name
        -   id: $$cap_mariadb_db
            label: MariaDB Database Name
            description: |-
                Name of the Database used by Photoview.  
                Normally, you won't need to change this.
            defaultValue: photoview

        # Variable for MariaDB Username
        -   id: $$cap_mariadb_user
            label: MariaDB Username
            description: |-
                Username for the Database used by Photoview.  
                Normally, you won't need to change this.
            defaultValue: photoview

        # Variable for MariaDB Password
        -   id: $$cap_mariadb_pass
            label: MariaDB Password
            description: |-
                Password for the Database used by Photoview.  
                Normally, you won't need to change this.
            defaultValue: $$cap_gen_random_hex(16)


# Define services
services:

    # Photoview service
    $$cap_appname:

        # Use official image
        image: viktorstrate/photoview:$$cap_appversion

        # Define the services this service depends on
        depends_on:

            # Start the database first, then photoview
            - $$cap_appname-db

        # Set hostname (f.e. photoview.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # We use a MySQL database, because it works much better for photoview
            PHOTOVIEW_DATABASE_DRIVER: mysql

            # Database Connection URL
            PHOTOVIEW_MYSQL_URL: $$cap_mariadb_user:$$cap_mariadb_pass@tcp(srv-captain--$$cap_appname-db)/$$cap_mariadb_db

            # Listen to 0.0.0.0
            PHOTOVIEW_LISTEN_IP: 0.0.0.0

            # Listen to port 80, so we don't have to specify containerHttpPort
            PHOTOVIEW_LISTEN_PORT: 80

            # Location of media cache
            PHOTOVIEW_MEDIA_CACHE: /app/cache

            # MapBox token for map related features
            MAPBOX_TOKEN: $$cap_mapbox_token

        # Define volumes
        volumes:

            # Volume containing media cache
            - $$cap_appname-media-cache:/app/cache

            # Volume containing photos and videos
            - $$cap_media_path:/data/media

    # MariaDB service
    $$cap_appname-db:

        # Use official image
        image: mariadb:$$cap_mariadb_appversion

        # Set hostname (f.e. photoview-db.demo.caprover.com)
        hostname: $$cap_appname-db.$$cap_root_domain

        # Define environment variables
        environment:

            # Use a random root password, because we don't need root access
            MYSQL_RANDOM_ROOT_PASSWORD: 1

            # Database Name
            MYSQL_DATABASE: $$cap_mariadb_db

            # Username
            MYSQL_USER: $$cap_mariadb_user

            # Password
            MYSQL_PASSWORD: $$cap_mariadb_pass

        # Define volumes
        volumes:

            # Persist database data
            - $$cap_appname-db-data:/var/lib/mysql

        # CapRover's special options
        caproverExtra:

            # Database, so don't expose as web app
            notExposeAsWebApp: true
