# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: Plex Media Server (Skayo)

    # Description displayed on the app list
    description: |-
        Plex organizes all of your personal media so you can enjoy it no matter where you are

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            ![Plex Logo](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-banner.png)

            ðŸŒ [Website](https://www.plex.tv/)
            ðŸ“– [Documentation](https://support.plex.tv/articles/)
            ðŸ“ [GitHub](https://github.com/plexinc/pms-docker)
            ðŸ³ [DockerHub](https://hub.docker.com/r/linuxserver/plex)
            ðŸŽ« [Go Premium](https://www.plex.tv/plex-pass/)

            With the easy-to-install Plex Media Server software and your Plex apps, available on all your favorite phones, tablets, streaming devices, gaming consoles, and smart TVs, you can stream your video, music, and photo collections any time, anywhere, to any device.

        # Displayed after deployment
        end: |-
            ðŸŽ‰ðŸŽ‰ðŸŽ‰ Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

            > *NOTE*: Make sure to allow all the required ports through your firewall!
            > Click [here](https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/) for a detailed description about each port.
            > This one-click-app template only makes the container expose the `32400` port.
            > Add others on the app config page if you need them.

    # Documentation Link
    documentation: https://support.plex.tv/articles/

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag to install.  
                Click [here](https://hub.docker.com/r/linuxserver/plex/tags) for a list of available tags.
            defaultValue: 1.24.5.5173-8dcc73a59-ls86
            validRegex: /^(?:(?:arm|amd)(?:64|32)(?:v\d+)?-)?(?:develop-?)?(?:version-)?(?:\d+)(?:\.\d+\.\d+(?:\.\d+)?)?(?:-[a-z0-9]+)?(?:-ls\d+)?$/

        # Variable for media path
        -   id: $$cap_media_path
            label: Media Path
            description: |-
                Specify the location of all your media (movies, TV shows, music, etc.).
            validRegex: /^(?:[a-zA-Z]:)?[\/\\]{0,2}(?:[.\/\\ ](?![.\/\\\n])|[^<>:"|?*.\/\\ \n])+$/

        # Variable for claim token
        -   id: $$cap_plex_claim
            label: Plex Claim Token (OPTIONAL)
            description: |-
                Optionally, you can obtain a claim token from [here](https://plex.tv/claim) and input it below.  
                Keep in mind that claim tokens expire within 4 minutes.
            validRegex: /^(?:claim-[a-zA-Z0-9]+)?$/

        # Variable for time zone
        -   id: $$cap_tz
            label: Time Zone
            description: |-
                Specify your system's time zone.  
                Click [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of available time zones.
            defaultValue: Europe/Vienna
            validRegex: /^\w+\/\w+$/

        # Variable for Process User ID
        -   id: $$cap_puid
            label: User ID
            description: |-
                Specify the User ID that the process should use.  
                Run `id <username>` on the host system to see your UID.
            defaultValue: 1000
            validRegex: /^-?\d+$/

        # Variable for Process Group ID
        -   id: $$cap_pgid
            label: Group ID
            description: |-
                Specify the Group ID that the process should use.  
                Run `id <username>` on the host system to see your GID.
            defaultValue: 1000
            validRegex: /^-?\d+$/


# Define services
services:

    # Plex service
    $$cap_appname:

        # Use image by linuxserver.io
        image: lscr.io/linuxserver/plex:$$cap_appversion

        # Set hostname (f.e. plex.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # Process User ID
            PUID: $$cap_puid

            # Process Group ID
            PGID: $$cap_pgid

            # Timezone
            TZ: $$cap_tz

            # Plex Claim Token
            PLEX_CLAIM: $$cap_plex_claim

        # Define volumes
        volumes:

            # Volume containing database data and config
            - $$cap_appname-config:/config

            # Volume containing media like movies and TV shows
            - $$cap_media_path:/data/media

        # Define ports
        ports:

            # This is the only required port - allows access to the Plex Media Server
            - 32400:32400

        # CapRover's special options
        caproverExtra:

            # Plex uses port 32400 for the web interface
            containerHttpPort: 32400
