# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: Radarr (Skayo)

    # Description displayed on the app list
    description: |-
        A fork of Sonarr to work with movies à la Couchpotato - Automatically downloads Movies for you

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            ![Radarr Logo](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr.png)

            🌐 [Website](https://radarr.video)
            📖 [Documentation](https://wiki.servarr.com/radarr)
            📁 [GitHub](https://github.com/Radarr/Radarr)
            🐳 [DockerHub](https://hub.docker.com/r/linuxserver/radarr)
            👛 [Donate](https://opencollective.com/radarr)

            Radarr is a movie collection manager for Usenet and BitTorrent users.
            It can monitor multiple RSS feeds for new movies and will interface with clients and indexers to grab, sort, and rename them.
            It can also be configured to automatically upgrade the quality of existing files in the library when a better quality format becomes available.

        # Displayed after deployment
        end: |-
            🎉🎉🎉 Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

    # Documentation Link
    documentation: https://wiki.servarr.com/radarr

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag to install.  
                Click [here](https://hub.docker.com/r/linuxserver/radarr/tags) for a list of available tags.
            defaultValue: 3.2.2.5080-ls121
            validRegex: /^(?:(?:arm|amd)(?:64|32)(?:v\d+)?-)?(?:develop-?)?(?:version-)?(?:\d+)(?:\.\d+\.\d+(?:\.\d+)?)?(?:-ls\d+)?$/

        # Variable for data path
        -   id: $$cap_data_path
            label: Data Path
            description: |-
                Specify the location of all your movies and downloads.
                > *NOTE*: It's best to use a single volume for movies and downloads, otherwise import will take **MUCH** longer!  
                > If you still want two different volumes, just change it on the app config page later on.
            validRegex: /^(?:[a-zA-Z]:)?[\/\\]{0,2}(?:[.\/\\ ](?![.\/\\\n])|[^<>:"|?*.\/\\ \n])+$/

        # Variable for time zone
        -   id: $$cap_tz
            label: Time Zone
            description: |-
                Specify your system's time zone.  
                Click [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of available time zones.
            defaultValue: Europe/Vienna
            validRegex: /^\w+\/\w+$/

        # Variable for Process User ID
        -   id: $$cap_puid
            label: User ID
            description: |-
                Specify the User ID that the process should use.  
                Run `id <username>` on the host system to see your UID.
            defaultValue: 1000
            validRegex: /^-?\d+$/

        # Variable for Process Group ID
        -   id: $$cap_pgid
            label: Group ID
            description: |-
                Specify the Group ID that the process should use.  
                Run `id <username>` on the host system to see your GID.
            defaultValue: 1000
            validRegex: /^-?\d+$/


# Define services
services:

    # Radarr service
    $$cap_appname:

        # Use image by linuxserver.io
        image: lscr.io/linuxserver/radarr:$$cap_appversion

        # Set hostname (f.e. radarr.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # Process User ID
            PUID: $$cap_puid

            # Process Group ID
            PGID: $$cap_pgid

            # Timezone
            TZ: $$cap_tz

        # Define volumes
        volumes:

            # Volume containing database data and config
            - $$cap_appname-config:/config

            # Volume containing movies and downloads
            - $$cap_data_path:/data

        # CapRover's special options
        caproverExtra:

            # Radarr uses port 7878
            containerHttpPort: 7878
