# Use schema version 4
captainVersion: 4


# One-click-app options
caproverOneClickApp:

    # App name
    displayName: Sonarr (Skayo)

    # Description displayed on the app list
    description: |-
        A smart PVR for Usenet and BitTorrent users - Automatically downloads TV Shows for you

    # Define instructions
    instructions:

        # Displayed one the app config page, where you enter all variable values
        start: |-
            ![Sonarr Logo](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-banner.png)

            ðŸŒ [Website](https://sonarr.tv/)
            ðŸ“– [Documentation](https://wiki.servarr.com/sonarr)
            ðŸ“ [GitHub](https://github.com/Sonarr/Sonarr)
            ðŸ³ [DockerHub](https://hub.docker.com/r/linuxserver/sonarr)
            ðŸ‘› [Donate](https://sonarr.tv/donate)

            Sonarr is a PVR for Usenet and BitTorrent users.
            It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them.
            It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.

        # Displayed after deployment
        end: |-
            ðŸŽ‰ðŸŽ‰ðŸŽ‰ Successfully deployed!  
            Check it out at: http://$$cap_appname.$$cap_root_domain

    # Documentation Link
    documentation: https://wiki.servarr.com/sonarr

    # Whether this one-click-app uses the official image or a trusted source
    isOfficial: true

    # Define variables
    variables:

        # Variable for version
        -   id: $$cap_appversion
            label: App Version
            description: |-
                Specify the version tag to install.  
                Click [here](https://hub.docker.com/r/linuxserver/sonarr/tags) for a list of available tags.
            defaultValue: 3.0.6.1342-ls128
            validRegex: /^(?:(?:arm|amd)(?:64|32)(?:v\d+)?-)?(?:develop-?)?(?:version-)?(?:\d+)(?:\.\d+\.\d+(?:\.\d+)?)?(?:-ls\d+)?$/

        # Variable for data path
        -   id: $$cap_data_path
            label: Data Path
            description: |-
                Specify the location of all your TV shows and downloads.
                > *NOTE*: It's best to use a single volume for TV shows and downloads, otherwise imports will take **MUCH** longer!  
                > If you still want two different volumes, just change it on the app config page later on.
            validRegex: /^(?:[a-zA-Z]:)?[\/\\]{0,2}(?:[.\/\\ ](?![.\/\\\n])|[^<>:"|?*.\/\\ \n])+$/

        # Variable for time zone
        -   id: $$cap_tz
            label: Time Zone
            description: |-
                Specify your system's time zone.  
                Click [here](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for a list of available time zones.
            defaultValue: Europe/Vienna
            validRegex: /^\w+\/\w+$/

        # Variable for Process User ID
        -   id: $$cap_puid
            label: User ID
            description: |-
                Specify the User ID that the process should use.  
                Run `id <username>` on the host system to see your UID.
            defaultValue: 1000
            validRegex: /^-?\d+$/

        # Variable for Process Group ID
        -   id: $$cap_pgid
            label: Group ID
            description: |-
                Specify the Group ID that the process should use.  
                Run `id <username>` on the host system to see your GID.
            defaultValue: 1000
            validRegex: /^-?\d+$/


# Define services
services:

    # Sonarr service
    $$cap_appname:

        # Use image by linuxserver.io
        image: lscr.io/linuxserver/sonarr:$$cap_appversion

        # Set hostname (f.e. sonarr.demo.caprover.com)
        hostname: $$cap_appname.$$cap_root_domain

        # Define environment variables
        environment:

            # Process User ID
            PUID: $$cap_puid

            # Process Group ID
            PGID: $$cap_pgid

            # Timezone
            TZ: $$cap_tz

        # Define volumes
        volumes:

            # Volume containing database data and config
            - $$cap_appname-config:/config

            # Volume containing TV shows and downloads
            - $$cap_data_path:/data

        # CapRover's special options
        caproverExtra:

            # Sonarr uses port 8989
            containerHttpPort: 8989
